/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.0   2018-06-29

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes ------------------------------------------------------------------*/
#include "nvic.h"
#include "SysTick.h"
#include "exti.h"
#include "gpio.h"
#include "dma.h"
#include "memcpy.h"

/* Private typedef */
/* Private define ------------------------------------------------------------*/
/**
 * @brief   Buffer array size
 */
#define BUFFER_SIZE     ((uint32_t) 500)

/**
 * @brief   use #define USE_MEMCPY or USE_DMA
 */
#define USE_DMA

/* Private macro */

/* Private variables ---------------------------------------------------------*/
/**
 * @brief   Source and destination buffers
 */
static uint32_t srcBuffer[BUFFER_SIZE];
static uint32_t dstBuffer[BUFFER_SIZE];

/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	SysTick_Init();
    GPIO_OnBoard_Init_LED();

    GPIO_Init_PB();
    EXTI_Init_PB();
    NVIC_Init();

    DMA_Init(1, DMA1_Channel3, dstBuffer, srcBuffer, BUFFER_SIZE, DMA_PERIPHERAL_DATA_32BIT, DMA_MEMORY_DATA_32BIT,
    		 DMA_PRIORITY_VERY_HIGH, DMA_PERIPHERAL_INCREMENT_E, DMA_MEMORY_INCREMENT_E, DMA_CIRCULAR_MODE_D,
			 DMA_M2M_E, DMA_READ_FROM_MEMORY);

    /* Initialize source buffer */
    for (int idx = 0; idx < BUFFER_SIZE; idx++)
    {
      srcBuffer[idx] = idx;
    }
    Yellow_LED_BITBAND = 1;
    __enable_irq();

      /* Signal start of coping data, by turning on Yellow LED */
    	Yellow_LED_BITBAND = 0;

      /* Copy data */
      #ifdef USE_MEMCPY
      ReturnStatus_Type returnResults = memcpy32(srcBuffer, dstBuffer, BUFFER_SIZE);

      /* Check return status */
      if(RETURN_STATUS_OK != returnResults)
      {
        /* Copying is not OK */

      }
      else
      {
        /* Copying is OK, Turn off Yellow LED */
    	   Yellow_LED_BITBAND = 1;
      }
      #endif

     #ifdef USE_DMA
      /* Clear PRIMASK, enable IRQs */

      /* DMA enable */
      DMA_ChannelEnable(DMA1_Channel3, 1,3);

      #endif
  while(1);

}


